### ISSUE TITLE
Not running on Device - Signing issue

### ISSUE THREAD

**Issue by tuarua** [tuarua/SwiftIOSANE#1]

**Comment by mistergreen** [comment]
This is the closest thing I can find. I think, when coding with Xcode, it signs the frameworks for you. I guess whatever IDE you're using does not.


> Benedikt_Rausch Aug 14, 2015 2:51 AM (in response to maqdev)
Hello guys,
 
we had to get dynamic libs working in our app, so we finally found a way to do this. It is a bit weird but well it works 
You have to add the .frameworks in the final app in the /Frameworks directory.
 
1. You have to sign the dynamic Frameworks with your entitlements.
To find your entitlements:
security find-identity -v -p codesigning
To sign your libs:
codesign --sign "###HASH WHICH YOU GET FROM THE LIST###" --force --all --option=library path/to/your/Framework.framework/
To check the signing of your libs:
codesign -vv -d "path/to/your/Framework.framework/"
 
After that we hit a block because Adobe signs the ipa without a Team Identifier ... which you can see wenn you unzip the ipa and check it with:
codesign -dvvv Payload/appname.app/
So you have to re-sign your .ipa to get the Team Identifier inside, there are two ways:
Use the app https://www.airsignapp.com/
Use XCode to resign it with this script: http://pastebin.com/pkedRxYH which also re-signs the app and you can run it direct in xcode.
I hope I could help you with the stuff.
Cheers
1 person found this helpful

**Comment by tuarua** [comment]
Packaging tool included
